env:
  GITHUB_USERNAME: mikispag
  GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  GOPRIVATE: 'github.com/mikispag/*'
name: Lint, build and test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  golangci:
    name: Lint, build and test
    runs-on: ubuntu-latest
    steps:
      - name: Configure git for private repos
        run: git config --global url."https://${GITHUB_USERNAME}:${GITHUB_PERSONAL_ACCESS_TOKEN}@github.com".insteadOf "https://github.com"
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: '--timeout=5m'
      - name: run
        uses: cedrickring/golang-action@1.6.0
